language: cpp

cache:
  directories:
  - ".cache"

before_install:
- mkdir -p .cache
- sudo apt-get update

install:
- ./ci/install_arm_gcc.sh
- ./platform/spark/firmware/ci/install_gcc.sh
- source ./ci/install_boost.sh

script:
- ./ci/build.sh

notifications:
  slack:
    secure: AoLzFHi7c7sRdcsMIzCgG3amg/1acImECO21Q3LXf6i6++ytqrvgTiQMQp9k1XJq+WVlrRiP7NDl3o8oMQv9nR/xrNXhosYHXVHAYY/B1nh4jl4pp8hPTMQUJcac64w1zbJMMqlABbawelVg8qF4zn+TNX+io8APERoycBpQgT4=

