language: cpp

sudo: required

services:
  - docker
  
script:
  - cd ./docker
  - docker-compose pull compiler
  - docker-compose run --rm compiler bash /firmware/app/brewbox/proto/generate_proto_cpp.sh
  - docker-compose run --rm compiler bash /firmware/app/brewblox/proto/generate_test_proto_cpp.sh
  - docker-compose run --rm compiler bash build-tests.sh
  - docker-compose run --rm compiler bash run-tests.sh
  - docker-compose run --rm compiler bash build-firmware.sh

notifications:
  slack:
    secure: AoLzFHi7c7sRdcsMIzCgG3amg/1acImECO21Q3LXf6i6++ytqrvgTiQMQp9k1XJq+WVlrRiP7NDl3o8oMQv9nR/xrNXhosYHXVHAYY/B1nh4jl4pp8hPTMQUJcac64w1zbJMMqlABbawelVg8qF4zn+TNX+io8APERoycBpQgT4=

