resources:
  repositories:
    - repository: self
  containers: 
    - container: compiler
      image: brewblox/firmware-compiler:arm-gcc-8
      
trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

#########################################################
# Tests
#########################################################
jobs:
  - job: Tests
    pool:
      vmImage: "Ubuntu-18.04"
    container: compiler

    steps:
      - checkout: self
        submodules: recursive
      
      - bash: |
          bash build/compile-proto.sh
        displayName: Compile proto

      - bash: |
          bash build/build-tests.sh
        displayName: Build tests

      - bash: |
          bash build/run-tests.sh
        displayName: Run tests

  #########################################################
  # Simulator
  #########################################################
  - job: SimulatorBinary
    pool:
      vmImage: "Ubuntu-18.04"
    container: compiler

    steps:
      - checkout: self
        submodules: recursive
      
      - bash: |
          bash build/compile-proto.sh
        displayName: Compile proto

      - script: make APP=brewblox PLATFORM=gcc
        workingDirectory: build

      - publish: $(System.DefaultWorkingDirectory)/build/target
        artifact: SimulatorBin


  #########################################################
  # Firmware Binaries
  #########################################################
  - job: FirmwareBinaries
    pool:
      vmImage: "Ubuntu-18.04"
    container: compiler

    steps:
      - checkout: self
        submodules: recursive
      
      - bash: |
          bash build/compile-proto.sh
        displayName: Compile proto

      - script: make APP=brewblox PLATFORM=p1
        workingDirectory: build
        displayName: Build p1
      
      - script: make APP=brewblox PLATFORM=photon
        workingDirectory: build
        displayName: Build photon
        
      - publish: $(System.DefaultWorkingDirectory)/build/target
        artifact: FirmwareBin


  #########################################################
  # Build Simulator Container
  #########################################################
  - job: SimulatorContainer
    pool:
      vmImage: "Ubuntu-18.04"
    dependsOn:
      - Tests
      - SimulatorBinary

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:  
          artifact: SimulatorBin
          path: $(Build.SourcesDirectory)/docker/simulator/target

      - bash: |
          docker build --no-cache -t brewblox/firmware-simulator:local simulator
        displayName: Build Image
        workingDirectory: docker

      - bash: |
          docker save brewblox/firmware-simulator:local > $(Build.ArtifactStagingDirectory)/simulator.tar
        workingDirectory: docker
        displayName: Save image

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)"
          artifactName: simulator      

  #########################################################
  # Build Firmware Binaries Container
  #########################################################
  - job: BinariesContainer
    pool:
      vmImage: "Ubuntu-18.04"
    dependsOn:
      - Tests
      - FirmwareBinaries

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:  
          artifact: FirmwareBin
          path: $(Build.SourcesDirectory)/target
      
      - bash: |
          bash build-bin.sh
        workingDirectory: docker
        displayName: Build Firmare bin container
        env:
          SKIP_BUILD: 1
  
      - bash: |
          docker save brewblox/firmware-bin:local > $(Build.ArtifactStagingDirectory)/bin.tar
        workingDirectory: docker
        displayName: Save image
  
      - task: PublishBuildArtifacts@1
        inputs:
          path: 
          pathtoPublish: "$(Build.ArtifactStagingDirectory)"
          artifactName: bin

  #########################################################
  # Deployment
  #########################################################
  - job: Deploy
    pool:
      vmImage: "Ubuntu-18.04"
    dependsOn:
      - Tests
      - SimulatorContainer
      - BinariesContainer

    variables:
      # Variables imported from brewblox group:
      # DOCKER_USER
      # DOCKER_PASSWORD
      # PYPI_USER
      # PYPI_PASSWORD
      - group: brewblox

    steps:
      - bash: |
          BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
          TAG=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
          echo "##vso[task.setvariable variable=brewblox.branch]$BRANCH"
          echo "##vso[task.setvariable variable=brewblox.tag]$TAG"
        displayName: export build variables

      - bash: |
          echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin docker.io
        displayName: Docker login
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: single
          artifactName: simulator
          downloadPath: $(System.ArtifactsDirectory)

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: single
          artifactName: bin
          downloadPath: $(System.ArtifactsDirectory)

      - bash: |
          docker load -i $(System.ArtifactsDirectory)/simulator/simulator.tar
          docker load -i $(System.ArtifactsDirectory)/bin/bin.tar
        displayName: Import images

      - bash: |
          bash push-local.sh ${SIM_REPO} newest-tag
          bash push-local.sh ${SIM_REPO} $(brewblox.tag)
          bash push-local.sh ${BIN_REPO} newest-tag
          bash push-local.sh ${BIN_REPO} $(brewblox.tag)
        displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits
        condition: and(succeeded(), variables['brewblox.tag'])
        workingDirectory: docker
        env:
          SIM_REPO: brewblox/firmware-simulator
          BIN_REPO: brewblox/firmware-bin

      - bash: |
          CLEAN_BRANCH=$(echo $(brewblox.branch) | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          bash push-local.sh ${SIM_REPO} ${CLEAN_BRANCH}
          bash push-local.sh ${BIN_REPO} ${CLEAN_BRANCH}
        displayName: Deploy branch to Docker Hub on any push to the GitHub repository
        condition: and(succeeded(), variables['brewblox.branch'], not(variables['brewblox.tag']))
        workingDirectory: docker
        env:
          SIM_REPO: brewblox/firmware-simulator
          BIN_REPO: brewblox/firmware-bin
