version: '2'
services:
  compiler:
    image: brewblox/firmware-compiler
    container_name: firmware-compiler
    privileged: true
    volumes:
        - ../:/firmware
    command: tail -f /dev/null

  simulator:
    image: brewblox/firmware-simulator:local
    privileged: true
    container_name: firmware-simulator
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        # brewblox protocol
        - "8332:8332"
        # http
        - "8380:80"

  coverage-simulator:
    image: brewblox/firmware-compiler
    container_name: firmware-coverage-simulator
    volumes:
        - ../:/firmware
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        # brewblox protocol
        - "8332:8332"
        # http
        - "8380:80"
        # websocket display emulation
        - "8380:7376"
    command: bash run-simulator.sh
