version: '2'
services:
  compiler:
    build: ./compiler/
    image: brewblox/firmware-compiler
    container_name: firmware-compiler
    volumes:
        - ../:/firmware
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
        
  simulator-compiler:
    build: ./simulator-compiler/
    image: brewblox/firmware-simulator-compiler
    container_name: firmware-simulator-compiler
    volumes:
        - ../:/firmware
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
        
  simulator:
    build: ./simulator/
    image: brewblox/firmware-simulator
    container_name: firmware-simulator
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "8332:8332"

networks:
    default:
      driver: bridge

