#! /usr/bin/env bash
set -e

echo "Flashing ESP32..."
esptool.py \
    --baud 460800 \
    --before default_reset \
    --after hard_reset \
    --chip esp32 \
    write_flash \
    --flash_mode dio \
    --flash_size detect \
    --flash_freq 40m \
    0x1000 ./bootloader-esp32.bin \
    0x8000 ./partition-table-esp32.bin \
    0x10000 ./brewblox-esp32.bin
echo "Your firmware has been updated."
